"""initial schema

Revision ID: 5dd7b8f7ebaf
Revises: 
Create Date: 2026-06-16 16:36:27.465974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dd7b8f7ebaf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('methodology_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('pillar_weights', sa.JSON(), nullable=False),
    sa.Column('released_at', sa.DateTime(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('scanners',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('org_name', sa.String(), nullable=False),
    sa.Column('api_key_hash', sa.String(), nullable=False),
    sa.Column('api_key_prefix', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('active', 'revoked', name='scanner_status_enum'), nullable=False),
    sa.Column('conformance_status', sa.Enum('conformant', 'pending', 'revoked', name='scanner_conformance_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('service_type', sa.Enum('ai_model', 'mcp_server', 'agent', name='service_type_enum'), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('identity_match_flags',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('service_id', sa.String(), nullable=False),
    sa.Column('incoming_identity', sa.JSON(), nullable=False),
    sa.Column('existing_identity', sa.JSON(), nullable=True),
    sa.Column('match_tier', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', name='flag_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('service_id', sa.String(), nullable=False),
    sa.Column('scanner_id', sa.String(), nullable=False),
    sa.Column('methodology_version_id', sa.String(), nullable=True),
    sa.Column('transparency_score', sa.Float(), nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('security_score', sa.Float(), nullable=False),
    sa.Column('privacy_score', sa.Float(), nullable=False),
    sa.Column('safety_societal_score', sa.Float(), nullable=False),
    sa.Column('excessive_agency_score', sa.Float(), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('coi_disclosed', sa.Boolean(), nullable=False),
    sa.Column('scored_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['methodology_version_id'], ['methodology_versions.id'], ),
    sa.ForeignKeyConstraint(['scanner_id'], ['scanners.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_score_service_scanner_created', 'scores', ['service_id', 'scanner_id', 'created_at'], unique=False)
    op.create_table('service_mcp_servers',
    sa.Column('service_id', sa.String(), nullable=False),
    sa.Column('target_service', sa.String(), nullable=False),
    sa.Column('provider_org', sa.String(), nullable=False),
    sa.Column('provider_tier', sa.Enum('official', 'platform_bundled', 'third_party', name='provider_tier_enum'), nullable=False),
    sa.Column('hosting_type', sa.Enum('hosted', 'self_hosted', name='hosting_type_enum'), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('service_id')
    )
    op.create_table('service_models',
    sa.Column('service_id', sa.String(), nullable=False),
    sa.Column('engine_provider', sa.String(), nullable=False),
    sa.Column('platform_provider', sa.String(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('service_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_models')
    op.drop_table('service_mcp_servers')
    op.drop_index('ix_score_service_scanner_created', table_name='scores')
    op.drop_table('scores')
    op.drop_table('identity_match_flags')
    op.drop_table('services')
    op.drop_table('scanners')
    op.drop_table('methodology_versions')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
